# ==========================================================
# 02-app-services.yaml
# Backend application services + Adminer DB UI
# Compatible with Minikube + Kafka external/internal setup
# ==========================================================

# --- Event Collector Service ---
apiVersion: v1
kind: Service
metadata:
  name: events-collector
  namespace: scalable-services
spec:
  selector:
    app: events-collector
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-collector
  namespace: scalable-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-collector
  template:
    metadata:
      labels:
        app: events-collector
    spec:
      containers:
        - name: events-collector
          image: real-time-events-collector:latest # Using local image
          imagePullPolicy: IfNotPresent # Change to IfNotPresent if using Docker Hub
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'kafka.scalable-services.svc.cluster.local:9092'
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
---
# --- Event Processor Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-processor
  namespace: scalable-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-processor
  template:
    metadata:
      labels:
        app: events-processor
    spec:
      initContainers:
        - name: wait-for-kafka-topic
          image: confluentinc/cp-kafka:7.0.1
          command:
            - sh
            - -c
            - |
              echo "Waiting for Kafka topic 'user-tracking-events'..."
              until kafka-topics --bootstrap-server kafka.scalable-services.svc.cluster.local:9092 --list | grep -q 'user-tracking-events'; do
                echo "Topic not found yet, sleeping..."
                sleep 5
              done
              echo "Topic 'user-tracking-events' found!"
        - name: wait-for-postgres
          image: postgres:13
          envFrom:
            - secretRef:
                name: postgres-secret
          command: ['sh', '-c', 'until pg_isready -h postgres.scalable-services.svc.cluster.local -p 5432 -U $POSTGRES_USER; do echo "Waiting for PostgreSQL..."; sleep 2; done;']
    spec:
      containers:
        - name: events-processor
          image: real-time-events-processor:latest # Using local image
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'kafka.scalable-services.svc.cluster.local:9092'
            - name: POSTGRES_HOST
              value: 'postgres.scalable-services.svc.cluster.local'
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

---
# --- Events API Service ---
apiVersion: v1
kind: Service
metadata:
  name: events-api
  namespace: scalable-services
spec:
  type: NodePort
  selector:
    app: events-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  namespace: scalable-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-api
  template:
    metadata:
      labels:
        app: events-api
    spec:
      containers:
        - name: events-api
          image: real-time-events-service:latest # Using local image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_HOST
              value: 'postgres.scalable-services.svc.cluster.local'
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 20
---
# --- Adminer (Database UI) ---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: scalable-services
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: scalable-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
# --- HPA for App Services ---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: events-collector-hpa
  namespace: scalable-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: events-collector
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: events-processor-hpa
  namespace: scalable-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: events-processor
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: events-api-hpa
  namespace: scalable-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: events-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
