# ==========================================================
# 03-frontend.yaml
# Frontend Next.js Application (served via Node)
# Compatible with Minikube + Scalable Services namespace
# ==========================================================

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: scalable-services
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: scalable-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: real-time-user-tracker-demo:latest
          imagePullPolicy: Never # Change to IfNotPresent if image comes from registry
          ports:
            - containerPort: 3000
          env:
            # Backend API inside the cluster
            - name: NEXT_PUBLIC_API_BASE_URL
              value: 'http://events-api:8001'

          # Health checks for stability
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 30
